apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
{{- if or (eq .Values.myapp.env "prod") (eq .Values.myapp.env "qa")}}
  replicas: 2
{{- else }}
  replicas: 1
{{- end }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/stacksimplify/kubenginx:4.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
