apiVersion: v2
name: 30-dependency-tags
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mychart4
    version: "0.1.0"
    repository: "https://stacksimplify.github.io/helm-charts/"
    alias: childchart4dev
    tags:
      - frontend
  - name: mychart4
    version: "0.1.0"
    repository: "https://stacksimplify.github.io/helm-charts/"
    alias: childchart4qa
    tags:
      - frontend
  - name: mychart2
    version: "0.1.0"
    repository: "https://stacksimplify.github.io/helm-charts/"
    alias: childchart2dev
    tags:
      - backend
  - name: mychart2
    version: "0.2.0"
    repository: "https://stacksimplify.github.io/helm-charts/"
    alias: childchart2qa
    tags:
      - backend
