apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: nginx
  annotations:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # Quote Function
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}
    # Functions in pipelines
    app.kubernetes.io/managed-by: {{ .Release.Service | squote | upper }}
    # Default Function
    app.kubernetes.io/name: {{ .Values.releaseName | default "defaultApp" }}
    # Controlling Leading and Trailing White Spaces
    leading-whitespace: "   {{- .Chart.Name }}   Mozer"
    trailing-whitespace: "   {{.Chart.Name -}}   Mozer"
    leadtrail-whitespace: "   {{- .Chart.Name -}}   Mozer"
    # Indent Function
    indenttest: "   {{- .Chart.Name | indent 4 -}}   "
    # Nindent Function
    nindenttest: "   {{- .Chart.Name | nindent 4 -}}   "

spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/stacksimplify/kubenginx:4.0.0
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 8080
