apiVersion: v1
kind: Pod
metadata:
  name: hook-postdelete
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  restartPolicy: Never
  containers:
    - name: hook-postdelete-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo post-delete hook Pod is running && sleep 5"]