apiVersion: v1
kind: Service
metadata:
  name: {{ include "43-sign-verify.fullname" . }}
  labels:
    {{- include "43-sign-verify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "43-sign-verify.selectorLabels" . | nindent 4 }}
