# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/stacksimplify/kubenginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

service:
  type: NodePort
  port: 80

exports:
  mychart4Data:
    mychart4Info:
      appName: kapp4
      appType: MicroService
      appDescription: Used for listing products
