apiVersion: v2
name: 33-import-values-explicit
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mychart4
    version: "0.1.0"
    repository: "file://charts/mychart4"
    import-values:
      - mychart4Data
  - name: mychart2
    version: "0.4.0"
    repository: "file://charts/mychart2"
