apiVersion: v1
kind: Pod
metadata:
  name: hook-preinstall
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
    "helm.sh/hook-weight": "2"
spec:
  restartPolicy: Never
  containers:
    - name: hook-preinstall-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo pre-install hook Pod 2 is running && sleep 5"]