# Default values for 46-validation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/stacksimplify/kubenginxhelm
  pullPolicy: IfNotPresent
  tag: ""