apiVersion: v1
kind: Pode
metadata:
  name: hook-postdelete
  annotations:
    "helm.sh/hook": "post-delete"
spec:
  restartPolicy: Never
  containers:
    - name: hook-postdelete-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c" "echo post-delete hook Pod is running && sleep 5"]