apiVersion: v1
kind: Pode
metadata:
  name: hook-preinstall
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  restartPolicy: Never
  containers:
    - name: hook-preinstall-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c" "echo pre-install hook Pod is running && sleep 5"]