apiVersion: v1
kind: Pode
metadata:
  name: hook-preupgrade
  annotations:
    "helm.sh/hook": "pre-upgrade"
spec:
  restartPolicy: Never
  containers:
    - name: hook-preupgrade-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c" "echo pre-upgrade hook Pod is running && sleep 5"]